library/ws-widget/collection/src/lib/card-home-discuss/card-home-discuss.component.html, library/ws-widget/collection/src/lib/card-home-discuss/card-home-discuss.component.scss, library/ws-widget/collection/src/lib/card-home-discuss/card-home-discuss.component.ts, library/ws-widget/collection/src/lib/card-home-discuss/card-home-discuss.module.ts
Changes for discuss UI in the home page
=> Task #54436 - Discuss card UI changes

library/ws-widget/collection/src/lib/_services/viewer-route-util.ts, package.json
1. fixed the videojs player issue for youtube.
2. resuming the video play after clicking back and playing again.
pending:
1. Content progress api is not triggering(wip)
2. telemetry is not triggering(wip)
=> youtube player fix

src/app/guards/empty-route.guard.ts, src/app/services/init.service.ts
Needs to merged to dev-portal branch!.
Holds the changes for initservice and empty route load
=> Task55090-Changes for initservice and empty route

library/ws-widget/collection/src/lib/_common/content-progress/content-progress.service.ts, library/ws-widget/collection/src/lib/_services/widget-user.service.ts, library/ws-widget/collection/src/lib/card-content/card-content.component.html, library/ws-widget/collection/src/lib/content-strip-multiple/content-strip-multiple.component.ts, library/ws-widget/collection/src/lib/content-strip-new-multiple/content-strip-new-multiple.component.ts, project/ws/app/src/lib/routes/app-toc/components/app-toc-banner/app-toc-banner.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-content-card/app-toc-content-card.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.ts, project/ws/app/src/lib/routes/events/components/right-menu-card/right-menu-card.component.ts, project/ws/app/src/lib/routes/events/routes/event-detail/event-detail.component.html, project/ws/app/src/lib/routes/search-v2/components/search-filters/search-filters.component.html, project/ws/app/src/lib/routes/search-v2/components/search-filters/search-filters.component.ts, project/ws/app/src/lib/routes/search-v2/routes/learn-search/learn-search.component.html, project/ws/app/src/lib/routes/search-v2/routes/learn-search/learn-search.component.ts, project/ws/app/src/lib/routes/search-v2/searchv2-routing.module.ts, project/ws/app/src/lib/routes/search-v2/services/gb-search.service.ts, project/ws/app/src/lib/routes/search/components/search-input-home/search-input-home.component.ts
=> Dev portal==> progress

library/ws-widget/collection/src/lib/_common/content-progress/content-progress.service.ts, library/ws-widget/collection/src/lib/_services/widget-user.service.ts, library/ws-widget/collection/src/lib/card-content/card-content.component.html, library/ws-widget/collection/src/lib/content-strip-multiple/content-strip-multiple.component.ts, library/ws-widget/collection/src/lib/content-strip-new-multiple/content-strip-new-multiple.component.ts, package.json, project/ws/app/src/lib/routes/app-toc/app-toc.module.ts, project/ws/app/src/lib/routes/app-toc/components/app-toc-banner/app-toc-banner.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-content-card/app-toc-content-card.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-content-card/app-toc-content-card.component.ts, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.ts, project/ws/app/src/lib/routes/events/components/right-menu-card/right-menu-card.component.ts, project/ws/app/src/lib/routes/events/routes/event-detail/event-detail.component.html, project/ws/app/src/lib/routes/search-v2/components/search-filters/search-filters.component.html, project/ws/app/src/lib/routes/search-v2/components/search-filters/search-filters.component.ts, project/ws/app/src/lib/routes/search-v2/routes/learn-search/learn-search.component.html, project/ws/app/src/lib/routes/search-v2/routes/learn-search/learn-search.component.ts, project/ws/app/src/lib/routes/search-v2/searchv2-routing.module.ts, project/ws/app/src/lib/routes/search-v2/services/gb-search.service.ts, project/ws/app/src/lib/routes/search/components/search-input-home/search-input-home.component.ts, yarn.lock
=> Dev portal=> circular Progress

project/ws/app/src/lib/routes/events/components/events-card/events-card.component.html, project/ws/app/src/lib/routes/events/components/events-card/events-card.component.scss, project/ws/app/src/lib/routes/events/routes/event-detail/event-detail.component.html, project/ws/app/src/lib/routes/events/routes/event-detail/event-detail.component.scss, project/ws/app/src/lib/routes/events/routes/events/events.component.ts
* Updated event fixes
* Updated attend event btn conditions
* Removed extra spaces & inline css
* Added ecml archive file type
* Updated search filters with JSON & changes
* Added condition for event status display
* Implemented infinite scroll in search page
* Fixed icon overlap issue in toc
* designation API call integration
* Fixed todays events & text overflows
=> Dev searchv2 (#152)

library/ws-widget/collection/src/lib/_common/content-rating-v2-dialog/content-rating-v2-dialog.component.ts, library/ws-widget/collection/src/lib/_services/videojs-util.ts, library/ws-widget/collection/src/lib/card-content/card-content.component.ts, library/ws-widget/collection/src/lib/player-pdf/player-pdf.component.ts, library/ws-widget/utils/src/lib/services/telemetry.service.ts, project/ws/app/src/lib/routes/app-toc/components/app-toc-content-card/app-toc-content-card.component.ts, project/ws/app/src/lib/routes/browse-by-competency/routes/all-competencies/all-competencies.component.ts, project/ws/app/src/lib/routes/search-v2/routes/learn-search/learn-search.component.ts, project/ws/viewer/src/lib/plugins/html/html.component.ts, project/ws/viewer/src/lib/routes/audio/audio.component.ts, project/ws/viewer/src/lib/routes/pdf/pdf.component.ts, project/ws/viewer/src/lib/routes/video/video.component.ts, project/ws/viewer/src/lib/routes/youtube/youtube.component.ts, proxy/localhost.proxy.json
=> telematory Fix 1.1

library/ws-widget/collection/src/lib/card-content/card-content.component.html
=> Image Quality Improved

library/ws-widget/collection/src/lib/card-content/card-content.component.scss, src/styles/_ws-vars.scss, yarn.lock
=> Poster Image Update 2

project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.ts
Dev portal: revertable Program play related changes
=> Dev portal: revertable Program play related changes

project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.ts
Program Play Pause and status related Updates
=> Program Play Pause and status

project/ws/app/src/lib/routes/competencies/routes/competence-all/competence-all.component.html, src/app/services/init.service.ts
Changes for nodebb user call removal and competency changes
=> Task 56069, 56313

angular.json, library/ws-widget/collection/src/lib/_common/certificate-dialog/certificate-dialog.module.ts, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.html, project/ws/app/src/lib/routes/app-toc/components/app-toc-home/app-toc-home.component.ts, tsconfig.json
BoostUp **build size** and **resource play** issue Fixed
=> BoostUp build size and resource play issue Fixed

project/ws/app/src/lib/routes/user-profile/components/user-profile/user-profile.component.ts, project/ws/app/src/lib/routes/user-profile/services/user-profile.service.ts
API is implemented for Personal Details, Professional Details, Certification & Skills tab. As Academics request data is modifing in the backed will implement that once API ready.
=> User profile new API implementation

project/ws/viewer/src/lib/plugins/practice/components/question/question.component.ts, project/ws/viewer/src/lib/plugins/practice/practice.component.ts, project/ws/viewer/src/lib/routes/practice-test/practice-test.component.ts
=> Dev portal player

project/ws/viewer/src/lib/plugins/practice/components/overview/overview.component.html, project/ws/viewer/src/lib/plugins/practice/components/overview/overview.component.scss, project/ws/viewer/src/lib/plugins/practice/components/question/question.component.html, project/ws/viewer/src/lib/plugins/practice/components/question/question.component.scss, project/ws/viewer/src/lib/plugins/practice/components/result/result.component.html, project/ws/viewer/src/lib/plugins/practice/components/result/result.component.scss, project/ws/viewer/src/lib/plugins/practice/practice.component.html, project/ws/viewer/src/lib/plugins/practice/practice.component.scss, project/ws/viewer/src/lib/route-view-container/practice/practice.component.html, src/styles/_ws-mixins.scss
=> Dev portal player UI

library/ws-widget/collection/src/lib/btn-page-back/btn-page-back.component.html, library/ws-widget/collection/src/lib/btn-page-back/btn-page-back.component.ts
=> Disabled explore button before login flow

project/ws/app/src/lib/routes/profile-v3/components/current-competency-card/current-competency-card.component.ts, project/ws/app/src/lib/routes/profile-v3/components/topic-card/topic-card.component.ts, project/ws/app/src/lib/routes/profile-v3/profile-v3.module.ts, project/ws/app/src/lib/routes/profile-v3/routes/current-competencies/current-competencies.component.html, project/ws/app/src/lib/routes/profile-v3/routes/current-competencies/current-competencies.component.ts
=> user onboarding fixes

proxy/localhost.proxy.json, src/app/services/app-interceptor.service.ts
=> Encode URI

project/ws/app/src/lib/routes/profile-v3/components/topic-card/topic-card.component.ts, project/ws/app/src/lib/routes/profile-v3/routes/topics/topic.component.ts, project/ws/app/src/lib/routes/profile-v3/services/topics.service.ts
Fixes Topic duplicacy & Topic toast msg
=> Fixes Topic duplicacy & Topic toast msg 

project/ws/viewer/src/lib/components/viewer-toc/viewer-toc.component.ts, project/ws/viewer/src/lib/components/viewer-top-bar/viewer-top-bar.component.ts
Updated the finish button condition in toc page, added a check if all resources status is 2 for showing the completion message
=> Nic setup errors

library/ws-widget/collection/src/lib/_common/content-rating-v2-dialog/content-rating-v2-dialog.component.ts, project/ws/viewer/src/lib/components/course-completion-dialog/course-completion-dialog.component.html, project/ws/viewer/src/lib/components/course-completion-dialog/course-completion-dialog.component.ts, project/ws/viewer/src/lib/components/course-completion-dialog/course-completion-dialog.module.ts, project/ws/viewer/src/lib/components/viewer-top-bar/viewer-top-bar.component.ts
TOC page rating link inside completion course
=> TOC page rating link

project/ws/app/src/lib/routes/user-profile/components/user-profile/user-profile.component.html, project/ws/app/src/lib/routes/user-profile/components/user-profile/user-profile.component.ts
=> Otp Validations Error messages added

project/ws/app/src/lib/routes/events/components/right-menu-card/right-menu-card.component.ts
For current events joining link is coming now, until event end time it will be shown.
=> Fixed current event join link issue in events hub
